apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-worker
  namespace: nodejs-kubernetes-microservices
  labels:
    app: job-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-worker
  template:
    metadata:
      labels:
        app: job-worker
    spec:
      containers:
        - name: job-worker
          image: your-docker-user/job-worker:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3001
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: PORT
              value: '3001'
          resources:
            requests:
              cpu: '200m'
              memory: '256Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 15
