services:
  redis:
    image: redis:alpine
    restart: unless-stopped

  api-gateway:
    build:
      context: ..
      dockerfile: apps/api-gateway/Dockerfile.prod
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - ./env-example/.env.api-gateway.prod

  job-worker:
    build:
      context: ..
      dockerfile: apps/job-worker/Dockerfile.prod
    restart: unless-stopped
    env_file:
      - ./env-example/.env.job-worker.prod
    deploy:
      replicas: 3

  stats-service:
    build:
      context: ..
      dockerfile: apps/stats-service/Dockerfile.prod
    restart: unless-stopped
    ports:
      - '3002:3002'
    env_file:
      - ./env-example/.env.stats-service.prod
