services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    env_file:
      - ./env/.env.redis
    volumes:
      - redis-data:/data

  api-gateway:
    build:
      context: ..
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./env/.env.api-gateway
    depends_on:
      - redis
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/apps/api-gateway/node_modules
      - /app/packages/shared/node_modules
      - /app/packages/shared/dist
    command: sh -c "pnpm --filter @nodejs-kubernetes-microservices/shared build && pnpm --filter @nodejs-kubernetes-microservices/api-gateway dev"

  job-worker:
    build:
      context: ..
      dockerfile: apps/job-worker/Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - ./env/.env.job-worker
    depends_on:
      - redis
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/apps/job-worker/node_modules
      - /app/packages/shared/node_modules
      - /app/packages/shared/dist #build of shared
    command: sh -c "pnpm --filter @nodejs-kubernetes-microservices/shared build && pnpm --filter @nodejs-kubernetes-microservices/job-worker dev"

  stats-service:
    build:
      context: ..
      dockerfile: apps/stats-service/Dockerfile
    ports:
      - '3002:3002'
    env_file:
      - ./env/.env.stats-service
    depends_on:
      - redis
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/apps/stats-service/node_modules
      - /app/packages/shared/node_modules
      - /app/packages/shared/dist
    command: sh -c "pnpm --filter @nodejs-kubernetes-microservices/shared build && pnpm --filter @nodejs-kubernetes-microservices/stats-service dev"

volumes:
  redis-data:
