apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-service
  namespace: nodejs-kubernetes-microservices
  labels:
    app: stats-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-service
  template:
    metadata:
      labels:
        app: stats-service
    spec:
      containers:
        - name: stats-service
          image: stats-service:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3002
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: PORT
              value: '3002'
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 15
