apiVersion: v1
kind: Service
metadata:
  name: stats-service
  namespace: nodejs-kubernetes-microservices
  labels:
    app: stats-service
spec:
  selector:
    app: stats-service
  ports:
    - name: http
      port: 3002
      targetPort: 3002
  type: ClusterIP
